# -*- coding: utf-8 -*-
"""Alarm_clock.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1K3zpEKRpFA-BEaut9YbNtL1qkL7XVMSt
"""

#SHEERAZ KHAN
#sheerazking006@gmail.com
#MINI PROJECT ( ALARM CLOCK USING PYTHON)

import datetime

import os

import time

import random

import webbrowser

# If video URL file does not exist, create one
if not os.path.isfile("youtube_alarm_videos.txt"):
	print('Creating "youtube_alarm_videos.txt"...')
	with open("youtube_alarm_videos.txt", "w") as alarm_file:
		alarm_file.write("https://www.youtube.com/watch?v=anM6uIZvx74")

def check_alarm_input(alarm_time):
	"""Checks to see if the user has entered in a valid alarm time"""
	if len(alarm_time) == 1: # [Hour] Format
		if alarm_time[0] < 24 and alarm_time[0] >= 0:
			return True
	if len(alarm_time) == 2: # [Hour:Minute] Format
		if alarm_time[0] < 24 and alarm_time[0] >= 0 and \
		   alarm_time[1] < 60 and alarm_time[1] >= 0:
			return True
	elif len(alarm_time) == 3: # [Hour:Minute:Second] Format
		if alarm_time[0] < 24 and alarm_time[0] >= 0 and \
		   alarm_time[1] < 60 and alarm_time[1] >= 0 and \
		   alarm_time[2] < 60 and alarm_time[2] >= 0:
			return True
	return False

# Get user input for the alarm time
print("Set a time for the alarm (Ex. 06:30 or 18:30:00)")
while True:
	alarm_input = input(">> ")
	try:
		alarm_time = [int(n) for n in alarm_input.split(":")]
		if check_alarm_input(alarm_time):
			break
		else:
			raise ValueError
	except ValueError:
		print("ERROR: Enter time in HH:MM or HH:MM:SS format")

# Time for the alarm to go off
print("Wake Up!")

# Load list of possible video URLs
with open("youtube_alarm_videos.txt", "r") as alarm_file:
	videos = alarm_file.readlines()

# Open a random video from the list
webbrowser.open(random.choice(videos))

